whisper:
  # Whisper implementation type: "faster-whisper", "whisper", "insanely-fast-whisper", or "voxtral-mini"
  whisper_type: voxtral-mini
  # Model size - for voxtral use "voxtral-mini-3b", for faster-whisper use "large-v3", etc.
  model_size: voxtral-mini-3b
  # Compute type. 'bfloat16' for CUDA with Voxtral, 'float16'/'int8' for faster-whisper, 'float32' for CPU.
  compute_type: bfloat16
  # Whether to offload the model after the inference.
  enable_offload: true

bgm_separation:
  # UVR model sizes between ["UVR-MDX-NET-Inst_HQ_4", "UVR-MDX-NET-Inst_3"]
  model_size: UVR-MDX-NET-Inst_HQ_4
  # Whether to offload the model after the inference. Should be true if your setup has a VRAM less than <16GB
  enable_offload: true
  # Device to load BGM separation model between ["cuda", "cpu", "xpu"]
  device: cuda

# Settings that apply to the `cache' directory. The output files for `/bgm-separation` are stored in the `cache' directory,
# (You can check out the actual generated files by testing `/bgm-separation`.)
# You can adjust the TTL/cleanup frequency of the files in the `cache' directory here.
cache:
  # TTL (Time-To-Live) in seconds, defaults to 10 minutes
  ttl: 600
  # Clean up frequency in seconds, defaults to 1 minutes
  frequency: 60

